import AuthProvider from "@/lib/auth-provider";
import ToastProvider from "@/lib/toast/toast-provider";
import { cn } from "@/lib/utils";
import { cal } from "@/styles/fonts";
import { NextUIProvider } from "@nextui-org/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, cal.variable,)}>
        <AuthProvider>
          <NextUIProvider className="h-screen w-screen text-foreground bg-background">
            <ToastProvider>{children}</ToastProvider>
          </NextUIProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
